const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    image: './images/banana.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'biryani',
    category: 'lunch',
    price: 13.99,
    image: './images/biryani.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    image: './images/shake pack.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'salad delight',
    category: 'breakfast',
    price: 20.99,
    image: './images/salad.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    image: './images/naan.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'strawberry shake',
    category: 'shakes',
    price: 18.99,
    image: './images/strawberry shake.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'toast',
    category: 'breakfast',
    price: 8.99,
    image: './images/toast.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'egg rice',
    category: 'lunch',
    price: 12.99,
    image: './images/egg rice.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'strawberry juice',
    category: 'shakes',
    price: 16.99,
    image: './images/strawberry juice.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'orange juice',
    category: 'mocktails',
    price: 16.99,
    image: './images/orange juice.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'virgin mojito',
    category: 'mocktails',
    price: 67.99,
    image: './images/mojito.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'blue ice',
    category: 'mocktails',
    price: 16.99,
    image: './images/blue ice.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'bluebrry cocktail',
    category: 'mocktails',
    price: 12.99,
    image: './images/bluebrry cocktail.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: 'lemon magrita',
    category: 'mocktails',
    price: 46.09,
    image: './images/lemon magrita.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: 'mixed cocktail',
    category: 'mocktails',
    price: 106.00,
    image: './images/mixed cocktail.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 16,
    title: 'chia pudding',
    category: 'shakes',
    price: 96.99,
    image: './images/chia pudding.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 17,
    title: 'classic mint',
    category: 'mocktails',
    price: 96.99,
    image: './images/mint.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 18,
    title: 'classic wine',
    category: 'Drinks',
    price: 236.99,
    image: './images/wine.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 19,
    title: 'pomegranate juice',
    category: 'mocktails',
    price: 126.99,
    image: './images/mixed fruit.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 20,
    title: 'pineapple icecream',
    category: 'dessert',
    price: 36.99,
    image: './images/piappple.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 21,
    title: 'death by choclate',
    category: 'dessert',
    price: 36.99,
    image: './images/sundae.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 22,
    title: 'berry icecream',
    category: 'dessert',
    price: 36.99,
    image: './images/berry icecream.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  
  {
    id: 24,
    title: 'red velvet',
    category: 'dessert',
    price: 36.99,
    image: './images/red velvet.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
